/* eslint-disable quote-props */
/* eslint-disable max-len */
/**
 * Translation file for this resource.
 *
 * This file is generated by combining automatic extraction and manual translations:
 * - The "en" (English) section is automatically extracted from source files
 * - Other language sections can be manually translated or pulled from Transifex
 * - When regenerating, existing manual translations are preserved when the English
 *   source text hasn't changed
 *
 * Structure:
 * - interface: translations for name/description (used by GUI formatMessage)
 * - extensions: translations for extension blocks (used by VM formatMessage)
 * - blocks: translations for Blockly blocks (used by Blockly.Msg)
 */

export default {
    'interface': {
        'en': {
            'microPythonRaspberryPiPico2.description': 'The next-generation Raspberry Pi Pico powered by the RP2350 dual-core chip with more memory and performance.'
        },
        'ru': {
            'microPythonRaspberryPiPico2.description': 'Следующее поколение Raspberry Pi Pico на двухъядерном чипе RP2350 с увеличенной памятью и производительностью.'
        },
        'zh-cn': {
            'microPythonRaspberryPiPico2.description': '基于 RP2350 双核芯片的新一代 Raspberry Pi Pico，更大内存与更强性能。'
        },
        'zh-tw': {
            'microPythonRaspberryPiPico2.description': '基於 RP2350 雙核晶片的新一代 Raspberry Pi Pico，更大記憶體與更強效能。'
        }
    },
    'extensions': {
        'en': {
            'microPythonRaspberryPiPico2.modeMenu.input': 'input',
            'microPythonRaspberryPiPico2.modeMenu.output': 'output',
            'microPythonRaspberryPiPico2.modeMenu.inputPullup': 'input-pullup',
            'microPythonRaspberryPiPico2.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonRaspberryPiPico2.levelMenu.high': 'high',
            'microPythonRaspberryPiPico2.levelMenu.low': 'low',
            'microPythonRaspberryPiPico2.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonRaspberryPiPico2.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonRaspberryPiPico2.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonRaspberryPiPico2.eolMenu.warp': 'warp',
            'microPythonRaspberryPiPico2.eolMenu.noWarp': 'no-warp',
            'microPythonRaspberryPiPico2.category.pins': 'Pins',
            'microPythonRaspberryPiPico2.category.serial': 'Serial',
            'microPythonRaspberryPiPico2.category.console': 'Console',
            'microPythonRaspberryPiPico2.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonRaspberryPiPico2.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonRaspberryPiPico2.pins.setPwmOutputU16': 'set pwm pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonRaspberryPiPico2.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonRaspberryPiPico2.pins.setServoOutputU16': 'set servo pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonRaspberryPiPico2.serial.raspberryPiPicoSerialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPico2.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonRaspberryPiPico2.serial.multiSerialReadALine': 'serial [NO] read a line',
            'microPythonRaspberryPiPico2.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonRaspberryPiPico2.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'ru': {
            'microPythonRaspberryPiPico2.modeMenu.input': 'input',
            'microPythonRaspberryPiPico2.modeMenu.output': 'output',
            'microPythonRaspberryPiPico2.modeMenu.inputPullup': 'input-pullup',
            'microPythonRaspberryPiPico2.modeMenu.inputPulldown': 'input-pulldown',
            'microPythonRaspberryPiPico2.levelMenu.high': 'high',
            'microPythonRaspberryPiPico2.levelMenu.low': 'low',
            'microPythonRaspberryPiPico2.InterrupModeMenu.risingEdge': 'rising edge',
            'microPythonRaspberryPiPico2.InterrupModeMenu.fallingEdge': 'falling edge',
            'microPythonRaspberryPiPico2.InterrupModeMenu.changeEdge': 'change edge',
            'microPythonRaspberryPiPico2.eolMenu.warp': 'warp',
            'microPythonRaspberryPiPico2.eolMenu.noWarp': 'no-warp',
            'microPythonRaspberryPiPico2.category.pins': 'Pins',
            'microPythonRaspberryPiPico2.category.serial': 'Serial',
            'microPythonRaspberryPiPico2.category.console': 'Console',
            'microPythonRaspberryPiPico2.pins.setPinMode': 'set pin [PIN] mode [MODE]',
            'microPythonRaspberryPiPico2.pins.setDigitalOutput': 'set digital pin [PIN] out [LEVEL]',
            'microPythonRaspberryPiPico2.pins.setPwmOutputU16': 'set pwm pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2.pins.readDigitalPin': 'read digital pin [PIN]',
            'microPythonRaspberryPiPico2.pins.readAnalogPin': 'read analog pin [PIN]',
            'microPythonRaspberryPiPico2.pins.setServoOutputU16': 'set servo pin [PIN] out [OUT]',
            'microPythonRaspberryPiPico2.pins.attachInterrupt': 'attach interrupt pin [PIN] mode [MODE] executes',
            'microPythonRaspberryPiPico2.serial.raspberryPiPicoSerialBegin': 'serial [NO] begin baudrate [BAUD] pin RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPico2.serial.multiSerialPrint': 'serial [NO] print [VALUE] [EOL]',
            'microPythonRaspberryPiPico2.serial.multiSerialReadALine': 'serial [NO] read a line',
            'microPythonRaspberryPiPico2.console.consolePrint': 'print [TEXT] [EOL]',
            'microPythonRaspberryPiPico2.console.consoleInput': 'prompt [TEXT] and read input'
        },
        'zh-cn': {
            'microPythonRaspberryPiPico2.modeMenu.input': '输入',
            'microPythonRaspberryPiPico2.modeMenu.output': '输出',
            'microPythonRaspberryPiPico2.modeMenu.inputPullup': '上拉输入',
            'microPythonRaspberryPiPico2.modeMenu.inputPulldown': '下拉输入',
            'microPythonRaspberryPiPico2.levelMenu.high': '高',
            'microPythonRaspberryPiPico2.levelMenu.low': '低',
            'microPythonRaspberryPiPico2.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonRaspberryPiPico2.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonRaspberryPiPico2.InterrupModeMenu.changeEdge': '电平变化',
            'microPythonRaspberryPiPico2.eolMenu.warp': '换行',
            'microPythonRaspberryPiPico2.eolMenu.noWarp': '不换行',
            'microPythonRaspberryPiPico2.category.pins': '引脚',
            'microPythonRaspberryPiPico2.category.serial': '串口',
            'microPythonRaspberryPiPico2.category.console': '控制台',
            'microPythonRaspberryPiPico2.pins.setPinMode': '设置引脚 [PIN] 模式为 [MODE]',
            'microPythonRaspberryPiPico2.pins.setDigitalOutput': '设置数字引脚 [PIN] 输出为 [LEVEL]',
            'microPythonRaspberryPiPico2.pins.setPwmOutputU16': '设置 PWM 引脚 [PIN] 输出为 [OUT]',
            'microPythonRaspberryPiPico2.pins.readDigitalPin': '读取数字引脚 [PIN]',
            'microPythonRaspberryPiPico2.pins.readAnalogPin': '读取模拟引脚 [PIN]',
            'microPythonRaspberryPiPico2.pins.setServoOutputU16': '设置舵机引脚 [PIN] 输出为 [OUT]',
            'microPythonRaspberryPiPico2.pins.attachInterrupt': '当引脚 [PIN] 检测到 [MODE] 时执行',
            'microPythonRaspberryPiPico2.serial.raspberryPiPicoSerialBegin': '串口 [NO] 初始化 波特率 [BAUD] 引脚 RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPico2.serial.multiSerialPrint': '串口 [NO] 打印 [VALUE] [EOL]',
            'microPythonRaspberryPiPico2.serial.multiSerialReadALine': '串口 [NO] 读取一行',
            'microPythonRaspberryPiPico2.console.consolePrint': '打印 [TEXT] [EOL]',
            'microPythonRaspberryPiPico2.console.consoleInput': '提示 [TEXT] 并读取输入'
        },
        'zh-tw': {
            'microPythonRaspberryPiPico2.modeMenu.input': '輸入',
            'microPythonRaspberryPiPico2.modeMenu.output': '輸出',
            'microPythonRaspberryPiPico2.modeMenu.inputPullup': '上拉輸入',
            'microPythonRaspberryPiPico2.modeMenu.inputPulldown': '下拉輸入',
            'microPythonRaspberryPiPico2.levelMenu.high': '高',
            'microPythonRaspberryPiPico2.levelMenu.low': '低',
            'microPythonRaspberryPiPico2.InterrupModeMenu.risingEdge': '上升沿',
            'microPythonRaspberryPiPico2.InterrupModeMenu.fallingEdge': '下降沿',
            'microPythonRaspberryPiPico2.InterrupModeMenu.changeEdge': '電平變化',
            'microPythonRaspberryPiPico2.eolMenu.warp': '換行',
            'microPythonRaspberryPiPico2.eolMenu.noWarp': '不換行',
            'microPythonRaspberryPiPico2.category.pins': '引腳',
            'microPythonRaspberryPiPico2.category.serial': '串列',
            'microPythonRaspberryPiPico2.category.console': '控制台',
            'microPythonRaspberryPiPico2.pins.setPinMode': '設定引腳 [PIN] 模式為 [MODE]',
            'microPythonRaspberryPiPico2.pins.setDigitalOutput': '設定數位引腳 [PIN] 輸出為 [LEVEL]',
            'microPythonRaspberryPiPico2.pins.setPwmOutputU16': '設定 PWM 引腳 [PIN] 輸出為 [OUT]',
            'microPythonRaspberryPiPico2.pins.readDigitalPin': '讀取數位引腳 [PIN]',
            'microPythonRaspberryPiPico2.pins.readAnalogPin': '讀取類比引腳 [PIN]',
            'microPythonRaspberryPiPico2.pins.setServoOutputU16': '設定伺服引腳 [PIN] 輸出為 [OUT]',
            'microPythonRaspberryPiPico2.pins.attachInterrupt': '當引腳 [PIN] 偵測到 [MODE] 時執行',
            'microPythonRaspberryPiPico2.serial.raspberryPiPicoSerialBegin': '串列 [NO] 初始化 鮑率 [BAUD] 接腳 RX [RX_PIN] TX [TX_PIN]',
            'microPythonRaspberryPiPico2.serial.multiSerialPrint': '串列 [NO] 印出 [VALUE] [EOL]',
            'microPythonRaspberryPiPico2.serial.multiSerialReadALine': '串列 [NO] 讀取一行',
            'microPythonRaspberryPiPico2.console.consolePrint': '印出 [TEXT] [EOL]',
            'microPythonRaspberryPiPico2.console.consoleInput': '提示 [TEXT] 並讀取輸入'
        }
    },
    'blocks': {
        'en': {},
        'ru': {},
        'zh-cn': {},
        'zh-tw': {}
    }
};
